// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAYgPd9qMhGRr6pZz_gOB4jTCdEdH9Sx9c',
    appId: '1:284324049246:web:5324a1227ee2ab910a5fcf',
    messagingSenderId: '284324049246',
    projectId: 'duit-a240d',
    authDomain: 'duit-a240d.firebaseapp.com',
    storageBucket: 'duit-a240d.appspot.com',
    measurementId: 'G-X3N7WDXWGZ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB0NSXmHSeiGHTr9KLI3gRSz_RwhdCD0QA',
    appId: '1:284324049246:android:55f875db4dfaa60f0a5fcf',
    messagingSenderId: '284324049246',
    projectId: 'duit-a240d',
    storageBucket: 'duit-a240d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDomVeLcjM8h1IrxdHkcT6eVZ3CiAaBCbU',
    appId: '1:284324049246:ios:1dc08eaa8dc890190a5fcf',
    messagingSenderId: '284324049246',
    projectId: 'duit-a240d',
    storageBucket: 'duit-a240d.appspot.com',
    iosClientId: '284324049246-fdrac5phco8gb8hpprkifsm9au9ictme.apps.googleusercontent.com',
    iosBundleId: 'com.example.agendaApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDomVeLcjM8h1IrxdHkcT6eVZ3CiAaBCbU',
    appId: '1:284324049246:ios:1dc08eaa8dc890190a5fcf',
    messagingSenderId: '284324049246',
    projectId: 'duit-a240d',
    storageBucket: 'duit-a240d.appspot.com',
    iosClientId: '284324049246-fdrac5phco8gb8hpprkifsm9au9ictme.apps.googleusercontent.com',
    iosBundleId: 'com.example.agendaApp',
  );
}
